// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKrDblriyRN8PjxnqpwIv3oFoO_HmFad8',
    appId: '1:998172981772:web:844ee45393e2d3a4b58c29',
    messagingSenderId: '998172981772',
    projectId: 'mingle-20ac5',
    authDomain: 'mingle-20ac5.firebaseapp.com',
    storageBucket: 'mingle-20ac5.appspot.com',
    measurementId: 'G-Q1VSHRYJYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0DdpEnDbWxNUHxK8RPTXY_MCJKxwVEAY',
    appId: '1:998172981772:android:4538f97dc2058eb7b58c29',
    messagingSenderId: '998172981772',
    projectId: 'mingle-20ac5',
    storageBucket: 'mingle-20ac5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9oTxfFMmXQh7Bw0OIyL86Sj-Kjfq0hNk',
    appId: '1:998172981772:ios:f069fb2b9b4c8a33b58c29',
    messagingSenderId: '998172981772',
    projectId: 'mingle-20ac5',
    storageBucket: 'mingle-20ac5.appspot.com',
    iosBundleId: 'com.MingleGlobal.mingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9oTxfFMmXQh7Bw0OIyL86Sj-Kjfq0hNk',
    appId: '1:998172981772:ios:afd1152b80a3bc47b58c29',
    messagingSenderId: '998172981772',
    projectId: 'mingle-20ac5',
    storageBucket: 'mingle-20ac5.appspot.com',
    iosBundleId: 'DanielsFlutterStudy.mingle.RunnerTests',
  );
}
