// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKjouJB2cRSKW5pwcAP2eTJSPJ9OsnM24',
    appId: '1:637637461782:web:5a7ea094bbb7792dd5f237',
    messagingSenderId: '637637461782',
    projectId: 'mingle-c9dd3',
    authDomain: 'mingle-c9dd3.firebaseapp.com',
    storageBucket: 'mingle-c9dd3.appspot.com',
    measurementId: 'G-LH6VTQJG8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvoVd2L--HIYE_FWS3tcDnGsEU4h_Fuk',
    appId: '1:637637461782:android:ddd5e6f4d43f67bdd5f237',
    messagingSenderId: '637637461782',
    projectId: 'mingle-c9dd3',
    storageBucket: 'mingle-c9dd3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOsobhLO10ZmKjuJZtGvoeL7IEJM0IOQY',
    appId: '1:637637461782:ios:8869c65a3e67e179d5f237',
    messagingSenderId: '637637461782',
    projectId: 'mingle-c9dd3',
    storageBucket: 'mingle-c9dd3.appspot.com',
    iosBundleId: 'com.TeamMingle.mingle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOsobhLO10ZmKjuJZtGvoeL7IEJM0IOQY',
    appId: '1:637637461782:ios:23c69d217a45285cd5f237',
    messagingSenderId: '637637461782',
    projectId: 'mingle-c9dd3',
    storageBucket: 'mingle-c9dd3.appspot.com',
    iosBundleId: 'DanielsFlutterStudy.mingle.RunnerTests',
  );
}
